# Generated by Django 5.2.7 on 2026-02-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='profile_pictures/default.svg', null=True, upload_to='profile_pictures/'),
        ),
    ]
