# Generated by Django 5.2.7 on 2026-02-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('shop', '0003_ingredient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'Articles de commande'},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='order_items', to='shop.ingredient'),
        ),
    ]
