# Generated by Django 5.2.7 on 2026-02-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_options_orderitem_ingredients'),
        ('shop', '0003_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='cart_items', to='shop.ingredient'),
        ),
    ]
